### ISSUE TITLE
License please?

### ISSUE THREAD

**Issue by not-napoleon** [mmai/wikilink#12]
Hello,

I'm interested in using and possibly contributing to this plugin, but currently there's no posted license which could make doing so technically illegal for me, even though the code is posted publicly.  Could you add a license file please?

Many vim plugins simply say they are licensed under the same terms as vim itself (Vim's license is found here: http://vimdoc.sourceforge.net/htmldoc/uganda.html#license).  You can find more choices here: https://opensource.org/licenses/alphabetical.  Vim's license is considered GPL compatible, so GPL is also an option if you prefer.  I would encourage you not to chose what the Apache org calls a "nonsensical" license, which has clauses that have no clear legal definition, such as "don't be a dick".  You can read more at https://www.apache.org/legal/resolved.html#what-can-we-not-include-in-an-asf-project-category-x

Thanks in advance.  I know this is a pretty boring ask, but unfortunately the current state of software copyrights requires us to attend to these things for everyone's protection.

**Comment by mmai** [comment]
Hello ! I've added the license. 

You could also be interested by [vim-markdown-wiki](https://github.com/mmai/vim-markdown-wiki) which uses markdown syntax instead of gollum.
